- name: Build Topology in CML
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for the lab file
      stat:
        path: "{{ virl_lab_file }}"
      register: stat_result
      delegate_to: localhost
      run_once: yes

    - assert:
        that:
          - stat_result.stat.exists
          - virl_host != ""
          - virl_username != ""
          - virl_password != ""
          - virl_lab != ""
        msg: "VIRL host, credentials, and topology file are required.  Verify the requirements in README are met."
      delegate_to: localhost
      run_once: yes

    - name: Create the lab
      virl_lab:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        lab: "{{ virl_lab }}"
        state: present
        file: "{{ virl_lab_file }}"
      register: results
