- import_playbook: waitfor-vmanage.yml

- import_playbook: refresh-cml.yml 

- import_playbook: check-vmanage.yml

- import_playbook: config-vmanage.yml

- import_playbook: import-templates.yml

- import_playbook: import-policy.yml

- import_playbook: attach-template.yml passed=sdwan_control:&virl_hosts

- import_playbook: activate-policy.yml
